import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {

  // ── SETTINGS ──────────────────────────────────────────────
  await prisma.setting.createMany({ skipDuplicates: true, data: [
    { key: 'site_name',        value: 'WildpathAfrica' },
    { key: 'site_tagline',     value: 'Where Every Path Leads to Wonder' },
    { key: 'site_email',       value: 'info@wildpathafrica.co.ke' },
    { key: 'site_phone',       value: '+254 700 000 000' },
    { key: 'site_whatsapp',    value: '+254700000000' },
    { key: 'site_address',     value: 'Nairobi, Kenya' },
    { key: 'social_facebook',  value: 'https://facebook.com/wildpathafrica' },
    { key: 'social_instagram', value: 'https://instagram.com/wildpathafrica' },
    { key: 'social_tiktok',    value: 'https://tiktok.com/@wildpathafrica' },
    { key: 'ga4_id',           value: '' },
    { key: 'currency',         value: 'KES' },
  ]})

  // ── COUNTRY: KENYA ────────────────────────────────────────
  const kenya = await prisma.country.upsert({
    where: { slug: 'kenya' },
    create: { name: 'Kenya', slug: 'kenya', continent: 'Africa', flagEmoji: '🇰🇪', sortOrder: 1, active: true },
    update: {}
  })

  // ── KENYA DESTINATIONS ────────────────────────────────────
  const destinations = [
    {
      name: 'Maasai Mara National Reserve',
      slug: 'maasai-mara',
      shortTeaser: 'Witness the Great Wildebeest Migration and encounter the Big Five on Kenya\'s most iconic savannah.',
      metaTitle: 'Maasai Mara Safari | Kenya\'s Greatest Wildlife Reserve | WildpathAfrica',
      metaDescription: 'Experience the Great Wildebeest Migration and Big Five in Maasai Mara. Book Kenya\'s most iconic safari with WildpathAfrica — expert guides, luxury lodges.',
      focusKeyword: 'Maasai Mara safari Kenya',
      secondaryKeywords: ['Great Wildebeest Migration', 'Big Five Kenya', 'Maasai Mara lodges', 'Kenya safari packages', 'Mara River crossing'],
      language: 'English, Swahili, Maasai',
      currency: 'KES / USD',
      timezone: 'EAT (UTC+3)',
      visaRequired: true,
      bestSeason: 'July–October (Migration); Year-round for Big Five',
      parkEntryResident: 'KES 400/day',
      parkEntryNonResident: 'USD 80/day',
      contentIntro: `The Maasai Mara National Reserve stands as Africa's most celebrated wildlife sanctuary, a vast sweep of golden savannah stretching across 1,510 square kilometres of southwestern Kenya's Narok County. Named after the Maasai people who have stewarded these lands for centuries, the Mara is a living monument to Africa's wildest instincts — where the ancient rhythms of predator and prey play out daily against a backdrop of endless sky and rippling grassland.

Immortalised by David Attenborough documentaries and celebrated by wildlife photographers worldwide, the Mara is most famous as the northern stage of the Great Wildebeest Migration — the largest movement of land mammals on Earth. Between July and October, over 1.5 million wildebeest, 300,000 zebras, and 500,000 Thomson's gazelles pour across the Mara River from Tanzania's Serengeti in a spectacle of raw, primal drama: crocodiles lurching from murky shallows, wildebeest leaping blindly into the current, dust rising in biblical columns above the crossing. Witnessing a Mara River crossing is not a wildlife sighting — it is a confrontation with life itself.

Yet the Maasai Mara is extraordinary in every month. Year-round, the reserve supports Kenya's densest concentrations of lion, with multiple prides occupying overlapping territories across the open plains. Cheetahs hunt in the golden afternoon light. Leopards drape themselves like liquid gold across acacia branches. Elephant families move in stately procession through the luggas. The Mara's permanent rivers — the Mara and Talek — sustain enormous hippo pods and crocodile populations that define the landscape even when the migration has passed south.

Beyond its wildlife, the Maasai Mara is the cultural heartland of the Maasai people — the tall, ochre-draped warriors whose relationship with wildlife is one of respectful coexistence stretching back generations. Authentic Maasai village visits, arranged with community consent, offer a window into boma life, traditional beadwork, jumping ceremonies, and the pastoralist philosophy that has kept this land wild when much of East Africa was converted to agriculture.`,
    },
    {
      name: 'Amboseli National Park',
      slug: 'amboseli',
      shortTeaser: 'Walk with giant elephant herds beneath the snow-capped peak of Mount Kilimanjaro.',
      metaTitle: 'Amboseli National Park | Elephants & Kilimanjaro Views | WildpathAfrica',
      metaDescription: 'Witness Kenya\'s majestic elephant herds against Mount Kilimanjaro in Amboseli National Park. Book your Amboseli safari with WildpathAfrica today.',
      focusKeyword: 'Amboseli National Park safari',
      secondaryKeywords: ['Amboseli elephants Kilimanjaro', 'Land of the Giants Kenya', 'Amboseli lodges', 'Kenya elephant safari'],
      language: 'English, Swahili, Maasai',
      currency: 'KES / USD',
      timezone: 'EAT (UTC+3)',
      visaRequired: true,
      bestSeason: 'June–October; January–February for clear Kilimanjaro views',
      parkEntryResident: 'KES 400/day',
      parkEntryNonResident: 'USD 60/day',
    },
    {
      name: 'Diani Beach',
      slug: 'diani-beach',
      shortTeaser: 'Stretch out on 25km of white coral sand lapped by the warm turquoise Indian Ocean.',
      metaTitle: 'Diani Beach Kenya | Africa\'s Best Beach Holiday | WildpathAfrica',
      metaDescription: 'Relax on Diani Beach — 25km of white sand and turquoise Indian Ocean. Snorkelling, diving, kite surfing. Book your Kenya beach holiday with WildpathAfrica.',
      focusKeyword: 'Diani Beach Kenya holiday',
      secondaryKeywords: ['best beach Kenya', 'Diani water sports', 'South Coast Kenya', 'Kisite Mpunguti marine park'],
      language: 'English, Swahili',
      currency: 'KES / USD',
      timezone: 'EAT (UTC+3)',
      visaRequired: true,
      bestSeason: 'December–March (calm seas); June–September (kite surfing)',
    },
    {
      name: 'Lake Nakuru National Park',
      slug: 'lake-nakuru',
      shortTeaser: 'A flamingo-fringed soda lake surrounded by acacia forest sheltering rhinos and lions.',
      metaTitle: 'Lake Nakuru National Park | Flamingos & Rhinos | WildpathAfrica',
      metaDescription: 'Visit Lake Nakuru for flamingos, endangered rhinos, and prolific birdlife in the heart of Kenya\'s Great Rift Valley. Book with WildpathAfrica.',
      focusKeyword: 'Lake Nakuru National Park Kenya',
      secondaryKeywords: ['Lake Nakuru flamingos', 'rhino Kenya safari', 'Rift Valley safari', 'Lake Nakuru birds'],
      language: 'English, Swahili',
      currency: 'KES / USD',
      timezone: 'EAT (UTC+3)',
      visaRequired: true,
      bestSeason: 'Year-round; June–September for bird concentrations',
    },
    {
      name: 'Tsavo East & West',
      slug: 'tsavo',
      shortTeaser: 'Kenya\'s largest wilderness — 22,000 sq km of red-dusted elephants, volcanic landscapes, and silent solitude.',
      metaTitle: 'Tsavo National Park Kenya | Kenya\'s Largest Wilderness | WildpathAfrica',
      metaDescription: 'Explore Tsavo East and West — Kenya\'s largest national park, famous for red elephants, Mzima Springs, and the Man-Eaters of Tsavo. Book with WildpathAfrica.',
      focusKeyword: 'Tsavo National Park Kenya safari',
      secondaryKeywords: ['Tsavo red elephants', 'Mzima Springs Kenya', 'Tsavo East vs West', 'Kenya wilderness safari'],
      language: 'English, Swahili',
      currency: 'KES / USD',
      timezone: 'EAT (UTC+3)',
      visaRequired: true,
      bestSeason: 'June–October; January–February',
    },
    {
      name: 'Nairobi',
      slug: 'nairobi',
      shortTeaser: 'The only capital city on Earth with a national park — lions roaming against a skyscraper skyline.',
      metaTitle: 'Nairobi Tourism | Safari, Culture & City Experiences | WildpathAfrica',
      metaDescription: 'Discover Nairobi — David Sheldrick Elephant Orphanage, Giraffe Centre, Nairobi National Park, and Kenya\'s vibrant food and art scene. Book with WildpathAfrica.',
      focusKeyword: 'Nairobi tourism Kenya',
      secondaryKeywords: ['Nairobi National Park', 'David Sheldrick Elephant Orphanage', 'Giraffe Centre Nairobi', 'things to do Nairobi'],
      language: 'English, Swahili',
      currency: 'KES',
      timezone: 'EAT (UTC+3)',
      visaRequired: true,
      bestSeason: 'Year-round',
    },
    {
      name: 'Mount Kenya & Aberdare',
      slug: 'mount-kenya',
      shortTeaser: 'Trek Africa\'s second-highest peak through moorlands, glacial tarns, and ancient forest.',
      metaTitle: 'Mount Kenya Trekking | Africa\'s Second Highest Mountain | WildpathAfrica',
      metaDescription: 'Climb Mount Kenya through Sirimon, Chogoria, or Naro Moru routes. Trek alpine moorlands, spot forest wildlife, and summit Point Lenana. Book with WildpathAfrica.',
      focusKeyword: 'Mount Kenya trekking climb',
      secondaryKeywords: ['Mount Kenya routes', 'Point Lenana summit', 'Aberdare National Park', 'Kenya mountain trekking'],
      language: 'English, Swahili',
      currency: 'KES / USD',
      timezone: 'EAT (UTC+3)',
      visaRequired: true,
      bestSeason: 'January–February; July–September',
    },
    {
      name: 'Samburu National Reserve',
      slug: 'samburu',
      shortTeaser: 'Remote northern Kenya where rare species found nowhere else roam untouched semi-arid wilderness.',
      metaTitle: 'Samburu National Reserve | Kenya\'s Northern Frontier Safari | WildpathAfrica',
      metaDescription: 'Discover Samburu\'s unique Northern Specials — reticulated giraffe, Grevy\'s zebra, Somali ostrich, and gerenuk. A rare, exclusive Kenya safari with WildpathAfrica.',
      focusKeyword: 'Samburu National Reserve safari Kenya',
      secondaryKeywords: ['Samburu Northern Specials', 'reticulated giraffe Kenya', 'northern Kenya safari', 'Samburu culture'],
      language: 'English, Swahili, Samburu',
      currency: 'KES / USD',
      timezone: 'EAT (UTC+3)',
      visaRequired: true,
      bestSeason: 'June–September; January–February',
    },
    {
      name: 'Watamu & Malindi',
      slug: 'watamu-malindi',
      shortTeaser: 'Kenya\'s marine heartland — UNESCO coral reefs, turtle nesting beaches, and Swahili history.',
      metaTitle: 'Watamu & Malindi Kenya | Marine Parks & Beaches | WildpathAfrica',
      metaDescription: 'Explore Watamu Marine National Park, sea turtles, world-class diving, and Malindi\'s Swahili heritage on Kenya\'s north coast. Book with WildpathAfrica.',
      focusKeyword: 'Watamu Malindi Kenya beach',
      secondaryKeywords: ['Watamu Marine National Park', 'Malindi diving', 'Kenya turtle watching', 'Gede Ruins Malindi'],
      language: 'English, Swahili',
      currency: 'KES / USD',
      timezone: 'EAT (UTC+3)',
      visaRequired: true,
      bestSeason: 'October–March (turtles); Year-round diving',
    },
    {
      name: 'Lamu Island',
      slug: 'lamu',
      shortTeaser: 'A UNESCO World Heritage island of whitewashed coral-stone houses, donkey-paths, and dhow-sailing sunsets.',
      metaTitle: 'Lamu Island Kenya | UNESCO World Heritage Culture & Dhow Sailing | WildpathAfrica',
      metaDescription: 'Escape to Lamu Island — Kenya\'s most authentic Swahili experience. Explore Lamu Old Town, sail traditional dhows, and relax on untouched beaches with WildpathAfrica.',
      focusKeyword: 'Lamu Island Kenya tourism',
      secondaryKeywords: ['Lamu Old Town UNESCO', 'dhow sailing Lamu', 'Lamu beaches Kenya', 'Swahili culture Kenya'],
      language: 'English, Swahili',
      currency: 'KES / USD',
      timezone: 'EAT (UTC+3)',
      visaRequired: true,
      bestSeason: 'July–September; January–March',
    },
  ]

  for (const dest of destinations) {
    await prisma.destination.upsert({
      where: { slug: dest.slug },
      create: { ...dest, countryId: kenya.id, status: 'PUBLISHED', secondaryKeywords: dest.secondaryKeywords || [] },
      update: {},
    })
  }

  // ── GLOBAL FAQs ───────────────────────────────────────────
  const faqs = [
    { category: 'Booking & Reservations', sortOrder: 1,
      question: 'How do I book a safari or tour with WildpathAfrica?',
      answer: 'Browse our tours and destinations on wildpathafrica.co.ke, click "Book Now" or "Get a Quote" on your chosen package, and complete the inquiry form. Our safari consultant will contact you within 24 hours to confirm availability. You can also WhatsApp us directly for instant assistance.' },
    { category: 'Booking & Reservations', sortOrder: 2,
      question: 'Can I book a private safari for my family or group?',
      answer: 'Absolutely. All WildpathAfrica tours can be arranged as fully private departures for couples, families, or corporate groups, offering maximum flexibility in timing, pace, and itinerary customization.' },
    { category: 'Booking & Reservations', sortOrder: 3,
      question: 'How far in advance should I book a Kenya safari?',
      answer: 'We recommend booking 4–8 weeks in advance for most tours. For peak season (July–October, Great Migration) and luxury Maasai Mara lodges, book 3–6 months ahead to secure availability.' },
    { category: 'Booking & Reservations', sortOrder: 4,
      question: 'Can I customize my safari itinerary?',
      answer: 'Yes — every WildpathAfrica package can be tailored to your preferred destinations, accommodation style, dietary requirements, and interests such as photography, birdwatching, or Maasai cultural experiences.' },
    { category: 'Booking & Reservations', sortOrder: 5,
      question: 'What is included in a typical WildpathAfrica safari package?',
      answer: 'Our standard packages include: 4×4 safari vehicle with professional guide-driver, accommodation as specified, meals as indicated (typically full board), game drives, KWS park entry fees, and airport transfers. Excluded unless specified: international flights, travel insurance, tips, and optional activities.' },
    { category: 'Booking & Reservations', sortOrder: 6,
      question: 'Do you offer solo traveller departures?',
      answer: 'Yes! Our group departure safaris are ideal for solo adventurers — small groups of 6–12 people led by an expert guide. A single supplement applies for private room occupancy.' },
    { category: 'Payment & Pricing', sortOrder: 1,
      question: 'What payment methods do you accept?',
      answer: 'WildpathAfrica accepts M-Pesa (Kenya preferred), Visa/Mastercard, bank transfer (local and international), PayPal, and cash (KES or USD at our Nairobi office). All online payments are SSL-encrypted.' },
    { category: 'Payment & Pricing', sortOrder: 2,
      question: 'Is a deposit required to confirm my booking?',
      answer: 'Yes. A 30% deposit is required to confirm your booking and secure lodge reservations. The balance is due 30 days before departure. Bookings made within 30 days require full payment at confirmation.' },
    { category: 'Payment & Pricing', sortOrder: 3,
      question: 'Are KWS park entry fees included in your prices?',
      answer: 'Yes. All Kenya Wildlife Service (KWS) park entry fees are included in our package prices unless clearly stated otherwise.' },
    { category: 'Payment & Pricing', sortOrder: 4,
      question: 'Do you offer installment payment options?',
      answer: 'For tours above KES 100,000 we offer a 3-installment plan: 30% deposit at booking, 40% at 60 days before departure, and 30% final at 14 days before departure.' },
    { category: 'Cancellation & Refunds', sortOrder: 1,
      question: 'What is the WildpathAfrica cancellation policy?',
      answer: '60+ days before departure: full refund minus 10% admin fee. 30–59 days: 50% refund. 15–29 days: 25% refund. Under 14 days: no refund (travel insurance strongly recommended). WildpathAfrica-initiated cancellations: 100% refund.' },
    { category: 'Cancellation & Refunds', sortOrder: 2,
      question: 'Do you recommend travel insurance?',
      answer: 'Strongly yes. We recommend comprehensive travel insurance covering trip cancellation, emergency medical evacuation (critical for remote safari areas), medical expenses, baggage loss, and flight delays.' },
    { category: 'Visas & Documentation', sortOrder: 1,
      question: 'Do I need a visa to visit Kenya?',
      answer: 'Most international visitors require a Kenya ETA (Electronic Travel Authorisation), applied for online at etakenya.go.ke before travel. It typically costs USD 30 and is processed within 72 hours.' },
    { category: 'Visas & Documentation', sortOrder: 2,
      question: 'What passport validity is required for Kenya?',
      answer: 'Your passport must be valid for at least 6 months beyond your planned departure date from Kenya, with at least 2 blank pages for entry/exit stamps.' },
    { category: 'Visas & Documentation', sortOrder: 3,
      question: 'Is yellow fever vaccination required?',
      answer: 'A yellow fever certificate is required if arriving from a yellow fever endemic country. Consult your doctor 6–8 weeks before travel for all recommended vaccinations including malaria prophylaxis.' },
    { category: 'Safari Experiences', sortOrder: 1,
      question: 'What is the Great Wildebeest Migration and when can I see it?',
      answer: 'The Great Wildebeest Migration sees over 1.5 million wildebeest and hundreds of thousands of zebra journey between Kenya\'s Maasai Mara and Tanzania\'s Serengeti. The most dramatic Mara River crossings occur July–October in the Maasai Mara.' },
    { category: 'Safari Experiences', sortOrder: 2,
      question: 'What are Kenya\'s Big Five and where do I see them?',
      answer: 'Kenya\'s Big Five are lion, elephant, buffalo, leopard, and rhinoceros. Best parks: Maasai Mara (lion, leopard, elephant, buffalo), Amboseli (elephant), Ol Pejeta (rhino), Lake Nakuru (rhino, lion), and Tsavo (all five in vast wilderness).' },
    { category: 'Safari Experiences', sortOrder: 3,
      question: 'Can I do a hot air balloon safari over the Maasai Mara?',
      answer: 'Yes — a balloon safari is one of the most extraordinary optional add-ons. Balloons launch at dawn for a sunrise drift over the plains, followed by a champagne bush breakfast. WildpathAfrica can arrange this (approximately USD 450–550 per person, paid locally).' },
    { category: 'Safari Experiences', sortOrder: 4,
      question: 'What is the best Kenya safari for families with children?',
      answer: 'We recommend Amboseli (flat terrain, exceptional elephant sightings) and Nairobi National Park for families with young children. Our dedicated Family Safari package features child-friendly pacing, age-appropriate activities, and family-suite lodge accommodations.' },
    { category: 'Accommodation & Food', sortOrder: 1,
      question: 'What types of accommodation are available on WildpathAfrica safaris?',
      answer: 'We offer accommodation across all budgets: budget camping and bandas, mid-range tented camps and lodges, luxury safari lodges, and ultra-luxury private conservancy camps. Our recommendation always matches your style and budget.' },
    { category: 'Accommodation & Food', sortOrder: 2,
      question: 'What is a tented camp — is it comfortable?',
      answer: 'Kenya\'s tented camps range from basic canvas to supremely luxurious permanent suites with en-suite bathrooms, wooden floors, and private verandahs overlooking the bush. Our luxury Mara tented camps are among the world\'s finest safari experiences.' },
    { category: 'Safety & Health', sortOrder: 1,
      question: 'Is it safe to travel to Kenya?',
      answer: 'Kenya\'s established national parks and reserves are very safe for tourists, managed by Kenya Wildlife Service with ranger patrols. WildpathAfrica continuously monitors KWS and government travel advisories. Our guides always prioritise client safety.' },
    { category: 'Safety & Health', sortOrder: 2,
      question: 'What should I pack for a Kenya safari?',
      answer: 'Neutral-coloured safari clothes (khaki, olive, brown), lightweight layers (mornings are cool), wide-brim hat, SPF 50+ sunscreen, sunglasses, binoculars, camera with zoom lens, insect repellent (DEET-based), and any personal medications.' },
    { category: 'Sustainability', sortOrder: 1,
      question: 'Is WildpathAfrica committed to sustainable tourism?',
      answer: 'Yes. We exclusively partner with KWS-licensed operators and eco-certified lodges, limit group sizes to reduce wildlife disturbance, support Maasai and local community enterprises, and offset carbon emissions for all ground transportation.' },
    { category: 'Sustainability', sortOrder: 2,
      question: 'How does my safari benefit local communities?',
      answer: 'Your safari directly funds conservation through KWS park fees. Conservancy stays pay Maasai landowners for wildlife access. We arrange community-benefit village visits and employ 50+ Kenyan guides, drivers, and staff — all Kenyan nationals.' },
  ]

  for (let i = 0; i < faqs.length; i++) {
    const f = faqs[i]
    await prisma.faq.create({ data: f }).catch(() => {})
  }

  console.log('✅ Database seeded: settings, Kenya country, 10 destinations, 24 global FAQs')
}

main().catch(console.error).finally(() => prisma.$disconnect())
